[MDC-1463][MDC-1466] simetbox-openwrt-simet-ma,lmapd: update versions
simetbox-openwrt-simet-lmapd: 0.15.5-2:

* Remove the main schedule from the builtin lmapd compile-time path,
  as required by the simet_lib_lmap API and simet-ma 0.18.7+
* initscript: partially switch to the multi-instance simet_lib_lmap.sh
  API.  Support only the main instance for now, keep most paths
  hardcoded.
* initscript: adjust permissions of /etc/simet and /etc/simet/lmap
  on start, if they deviate from the expected.  For reload, adjust
  only /etc/simet/lmap/*.json

Requires simet-ma 0.18.7+.

simetbox-openwrt-simet-ma: 0.18.11-1:

* Update Config help text for SIMET2_SPOOFER (no longer experimental,
  doesn't require openssl), add version of OpenWRT Chaos Calmer to
  the help text for SIMETBOX_APPLINK.
* Improve postinst to ensure there's a main schedule in place, and
  that the AGENT_LOCK is reset
* sspooferc needs to be SUID root (required to avoid the mess with
  filesystem capability support.  It just needs CAP_NET_RAW).
  chmod g+s it using an uci-defaults script.
* Switch simetbox_refresh_cron to the simet_lib_lmapd API.
* rpcd, init.d: run simet_register-ma.sh and
  simetbox_lmap-fetch-schedule.sh as user nicbr-simet
* simet_register-ma hooks: do not attempt to use the initscript to
  reload simet-ma, send SIGHUP to inetupc directly.
* hotplug.d/iface: reloads/starts simet-ma, starts simet-lmapd
  (can't reload simet-lmapd, it would be disruptive)
* cron.daily: start simet-ma as well, not just simet-lmapd
* Remove uci simet_ma.ixbr_ping config entries, that measurement
  does not exist anymore
* Remove ixbr_ping entries from ubus rpcd script

diff --git a/simetbox-openwrt-simet-lmapd/files/etc/init.d/simet-lmapd b/simetbox-openwrt-simet-lmapd/files/etc/init.d/simet-lmapd
--- a/simetbox-openwrt-simet-lmapd/files/etc/init.d/simet-lmapd
+++ b/simetbox-openwrt-simet-lmapd/files/etc/init.d/simet-lmapd
@@ -7,30 +7,88 @@ START=99
 STOP=10
 USE_PROCD=1
 
+# Note: multi-instance not supported yet
+LMAP_INSTANCE_LIST=main
 LMAP_OPTS="-j"
+
+do_prepare_common() {
+	# SIMET_CFG_LOAD_ERROR is also internally set in simet_lib_config.sh
+	SIMET_CFG_LOAD_ERROR=
+	. /usr/lib/simet/simet_lib_config.sh || SIMET_CFG_LOAD_ERROR=1
+	if [ -n "$SIMET_CFG_LOAD_ERROR" ] ; then
+		echo "$0: syntax errors in the configuration files, aborting..." >&2
+		return 1
+	fi
+	. /usr/lib/simet/simet_lib_lmapd.sh || {
+		echo "$0: failed to load simet_lib_lmapd.sh, aborting..." >&2
+		return 1
+	}
+	#shellcheck disable=SC2015
+	LMAP_INSTANCE_LIST=$(lmapd_get_instance_list) && [ -n "$LMAP_INSTANCE_LIST" ] || {
+		echo "$0: simet_lib_lmapd.sh::lmapd_get_instance_list failed, aborting..." >&2
+		return 1
+	}
+}
+
+x_paranoid_mkdir() {
+	[ -z "$1" ] && {
+		printf "%s: internal error, missing path to paranoid_mkdir\n", "$0" >&2
+		return 2
+	}
+	MKDIRMODE="$2" || :
+	[ -z "$MKDIRMODE" ] && MKDIRMODE=02770
+	#shellcheck disable=SC2015,SC2174
+	[ -n "$1" ] && mkdir -p -m 0700 "$1" && [ -d "$1" ] || {
+		printf "%s: failed to create directory %s\n" "$0" "$1" >&2
+		return 1
+	}
+	find "$1" -maxdepth 0 -type d ! -group nicbr-simet -exec chgrp nicbr-simet '{}' +
+	find "$1" -maxdepth 0 -type d ! -perm "$MKDIRMODE" -exec chmod "$MKDIRMODE" '{}' +
+	:
+}
+
+x_force_group_files() {
+	#shellcheck disable=SC2015
+	[ -n "$1" ] && [ -d "$1" ] || {
+		printf "%s: not a directory: %s" "$0" "$1" >&2
+		return 1
+	}
+	find "$1" -type f ! \( -user nicbr-simet -a -group nicbr-simet \) -exec chown "nicbr-simet:nicbr-simet" '{}' +
+	find "$1" -type f ! -perm -g+r -exec chmod g+r '{}' +
+	:
+}
 
 #note: also sourced by cronjob to self-heal permissions
 init_lmapd_fs() {
-	mkdir -p /var/run/lmapd
-	chown nicbr-simet:nicbr-simet /var/run/lmapd \
-		&& chmod 02775 /var/run/lmapd
-	mkdir -p /var/spool/lmapd/queue
-	chown -R nicbr-simet:nicbr-simet /var/spool/lmapd \
-		&& chmod 02770 /var/spool/lmapd /var/spool/lmapd/queue
+	do_prepare_common || exit 2
+
+	x_paranoid_mkdir /var/run/lmapd 02775
+	x_force_group_files /var/run/lmapd
+	x_paranoid_mkdir /var/spool/lmapd 02770
+	x_paranoid_mkdir /var/spool/lmapd/queue 02770
+	x_paranoid_mkdir /var/spool/lmapd/reports 02770
+	[ -d /var/spool/lmapd ] && {
+		find /var/spool/lmapd -type d ! -group nicbr-simet -exec chgrp nicbr-simet '{}' +
+		find /var/spool/lmapd -type d ! -perm -g+rwsx -exec chmod g+rwsx,o= '{}' +
+	}
+	x_force_group_files /var/spool/lmapd
+
 	# might race a fetch script, and we don't want to clobber the
 	# downloaded schedule, so ln -s (not -sf), which might fail
 	[ -e /var/run/lmapd/lmap-schedule.json ] || \
 		ln -s /usr/lib/simet/lmap-emergency-schedule.json \
 		      /var/run/lmapd/lmap-schedule.json 2>/dev/null || true
 	chown -h nicbr-simet:nicbr-simet /var/run/lmapd/*json || true
-	find /var/run/lmapd -type f -name '*json' \! -perm -0660 -exec chmod ug+rw,o-w {} +
-	find /var/run/lmapd -perm -0002 -exec chmod o-w {} +
-	find /etc/simet/lmap -type f \! -perm -0660 -exec chmod ug+rw,o-w {} +
+	find /var/run/lmapd -type f -name '*json' ! -perm -0660 -exec chmod ug+rw,o-w '{}' +
+	find /var/run/lmapd -perm -0002 -exec chmod o-w '{}' +
+
+	x_paranoid_mkdir /etc/simet 02770
+	x_paranoid_mkdir /etc/simet/lmap 02770
+	find /etc/simet -type f ! \( -user nicbr-simet -a -group nicbr-simet \) -exec chown "nicbr-simet:nicbr-simet" '{}' +
+	find /etc/simet -type f ! -perm -0660 -exec chmod ug+rw,o= '{}' +
 }
 
 # FIXME: refuse to start the lmapd if the engine is disabled
-#        refuse to start the lmapd if the MA is not registered?
-#        (we handle registering and schedule download in simet-ma)
 boot() {
 	init_lmapd_fs
 	# delay start of the measurement engine to lessen the RAM+CPU
@@ -40,9 +98,16 @@ boot() {
 }
 
 reload_service() {
+	do_prepare_common
+
 	chown -h nicbr-simet:nicbr-simet /var/run/lmapd/*json 2>/dev/null || true
-	if lmapctl $LMAP_OPTS validate ; then
-		lmapctl $LMAP_OPTS reload
+	find /var/run/lmapd -type f -name '*json' \! -perm -0660 -exec chmod ug+rw,o-w {} +
+
+	find /etc/simet/lmap -type f -name '*.json' ! \( -user nicbr-simet -a -group nicbr-simet \) -exec chown "nicbr-simet:nicbr-simet" '{}' +
+	find /etc/simet/lmap -type f -name '*.json' ! -perm -0660 -exec chmod ug+rw,o= '{}' +
+
+	if lmapd_lmapctl_validate "$(lmapd_get_sched_filename main)" >/dev/null 2>&1 ; then
+		lmapd_lmapctl_reload main
 		return 0
 	else
 		echo "%0: lmapd configuration invalid, not reloading" >&2
@@ -52,13 +117,19 @@ reload_service() {
 
 start_service() {
 	init_lmapd_fs
+
+	[ -n "$LMAP_RUN_DIR_PREFIX" ] || return 2
+	QDIR=$(lmapd_get_queuedir main) && [ -d "$QDIR" ] || return 1
+	RDIR=$(lmapd_get_rundir main) && [ -d "$RDIR" ] || return 1
+	SCHEDULE=$(lmapd_get_sched_filename main) && [ -n "$SCHEDULE" ] || return 1
+
 	procd_open_instance simet-lmapd
 	procd_set_param user nicbr-simet
 	procd_set_param respawn 1800 60 10
 	procd_set_param stderr 1
 	procd_set_param stdout 1
-	procd_set_param command /usr/bin/lmapd $LMAP_OPTS
-	lmapctl validate || procd_set_param error "lmapd configuration invalid"
+	procd_set_param command /usr/bin/lmapd $LMAP_OPTS -q "$QDIR" -r "$RDIR" -c+ -c "$SCHEDULE"
+	lmapd_lmapctl_validate "$SCHEDULE" || procd_set_param error "lmapd configuration invalid"
 	procd_close_instance
 }
 
diff --git a/simetbox-openwrt-simet-ma/files/etc/init.d/simet-ma b/simetbox-openwrt-simet-ma/files/etc/init.d/simet-ma
--- a/simetbox-openwrt-simet-ma/files/etc/init.d/simet-ma
+++ b/simetbox-openwrt-simet-ma/files/etc/init.d/simet-ma
@@ -14,7 +14,7 @@ simet_config() {
 	if [ $RC -ne 0 ] || [ -z "$AGENT_ID_FILE" ] || [ -z "$AGENT_TOKEN_FILE" ] || \
 		[ -z "$GEOLOC_CACHE" ] || [ -z "$SIMET_INETUP_SERVER" ] ; then
 		echo "$0: required configuration missing, aborting..." >&2
-		exit 1
+		return 1
 	fi
 
 	BOXID=$(get_mac_address.sh 2>/dev/null | tr A-F a-f | tr -d ': -') || :
@@ -38,36 +38,102 @@ simet_netconfig() {
 	}
 }
 
-boot() {
-	simet_config
+x_paranoid_mkdir() {
+	[ -z "$1" ] && {
+		printf "%s: internal error, missing path to paranoid_mkdir\n", "$0" >&2
+		return 2
+	}
+	MKDIRMODE="$2" || :
+	[ -z "$MKDIRMODE" ] && MKDIRMODE=02770
+	#shellcheck disable=SC2015,SC2174
+	[ -n "$1" ] && mkdir -p -m 0700 "$1" && [ -d "$1" ] || {
+		printf "%s: failed to create directory %s\n" "$0" "$1" >&2
+		return 1
+	}
+	find "$1" -maxdepth 0 -type d ! -group nicbr-simet -exec chgrp nicbr-simet '{}' +
+	find "$1" -maxdepth 0 -type d ! -perm "$MKDIRMODE" -exec chmod "$MKDIRMODE" '{}' +
+	:
+}
+
+x_force_group_files_mask_mode() {
+	#shellcheck disable=SC2015
+	[ -n "$1" ] && [ -d "$1" ] || {
+		printf "%s: not a directory: %s" "$0" "$1" >&2
+		return 1
+	}
+	FMASK="$2" || :
+	[ -z "$FMASK" ] && FMASK="0660"
+	FMODE="$3" || :
+	[ -z "$FMODE" ] && FMODE="ug+rw,o="
+	find "$1" -type f ! \( -user nicbr-simet -a -group nicbr-simet \) -exec chown "nicbr-simet:nicbr-simet" '{}' +
+	find "$1" -type f ! -perm "-$FMASK" -exec chmod "$FMODE" '{}' +
+	:
+}
+
+x_force_file_mode() {
+	#shellcheck disable=SC2015
+	[ -n "$1" ] && [ -e "$1" ] || return 0
+	[ -f "$1" ] || {
+		printf "%s: not a file: %s" "$0" "$1" >&2
+		return 1
+	}
+	FMASK="$2" || :
+	[ -z "$FMASK" ] && FMASK="0660"
+	FMODE="$3" || :
+	[ -z "$FMODE" ] && FMODE="ug+rw,o="
+	find "$1" -maxdepth 0 -type f ! \( -group nicbr-simet \) -exec chgrp -h "nicbr-simet" '{}' +
+	find "$1" -maxdepth 0 -type f ! -perm "-$FMASK" -exec chmod "$FMODE" '{}' +
+}
+
+#note: also sourced by cronjob to self-heal permissions
+init_simetma_fs() {
+	simet_config || return $?
 
 	# used for the geolocation cache and ephemeral tokens
-	[ -n "$SIMET_RUNSTATE_DIR" ] && mkdir -m 02770 -p "$SIMET_RUNSTATE_DIR" && chgrp nicbr-simet "$SIMET_RUNSTATE_DIR"
-	[ -n "$SIMET_LOCK_DIR" ] && mkdir -m 0770 -p "$SIMET_LOCK_DIR" && chgrp nicbr-simet "$SIMET_LOCK_DIR"
-	[ -n "$SIMET_PUBRUNSTATE_DIR" ] && \
-		mkdir -m 0770 -p "$SIMET_PUBRUNSTATE_DIR" && \
-		chgrp nicbr-simet "$SIMET_PUBRUNSTATE_DIR" && \
-		chmod 0775 "$SIMET_PUBRUNSTATE_DIR"
-	find "$AGENT_ID_FILE" -type f \! -perm -0660 -exec chmod ug+rw,o-w {} \; 2>/dev/null
-	find "$AGENT_TOKEN_FILE" -type f \! -perm -0660 -exec chmod ug+rw,o-w {} \; 2>/dev/null
-	find "$AGENT_VIEW_CREDENTIALS_FILE" -type f \! -perm -0664 -exec chmod ug+rw,o=r {} \; 2>/dev/null
+	[ -n "$SIMET_RUNSTATE_DIR" ] && {
+		x_paranoid_mkdir "$SIMET_RUNSTATE_DIR" 02770
+		x_force_group_files_mask_mode "$SIMET_RUNSTATE_DIR" 0660 "ug+rw,o="
+	}
+	[ -n "$SIMET_LOCK_DIR" ] && {
+		x_paranoid_mkdir "$SIMET_LOCK_DIR" 0770
+		x_force_group_files_mask_mode "$SIMET_LOCK_DIR" 0640 "u+rw,g+r"
+	}
+	[ -n "$SIMET_PUBRUNSTATE_DIR" ] && {
+		x_paranoid_mkdir "$SIMET_PUBRUNSTATE_DIR" 0775
+		x_force_group_files_mask_mode "$SIMET_PUBRUNSTATE_DIR" 0664 "ug+rw,o+r"
+	}
+
+	x_paranoid_mkdir /etc/simet 02770
+	find /etc/simet -type f ! \( -user nicbr-simet -a -group nicbr-simet \) -exec chown "nicbr-simet:nicbr-simet" '{}' +
+	find /etc/simet -type f ! -perm -0660 -exec chmod ug+rw,o= '{}' +
 	find /etc/simet -perm -0002 -exec chmod o-w {} + 2>/dev/null
+
+	x_force_file_mode "$AGENT_ID_FILE" 0660 "ug+rw,o-w"
+	x_force_file_mode "$AGENT_TOKEN_FILE" 0660 "ug+rw,o-w"
+	x_force_file_mode "$AGENT_VIEW_CREDENTIALS_FILE" 0664 "ug+rw,o=r"
+}
+
+boot() {
+	init_simetma_fs || return $?
 
 	# restoring config backups from other units is a problem we must check for on boot
 	simet_create_vlabel.sh >/dev/null 2>&1 || :
 
 	# warning: try to keep RAM load down for 32MiB devices!
-	( simet_register_ma.sh && {
+        ( start-stop-daemon -S -c nicbr-simet:nicbr-simet -n simet_reg_ma \
+                          -x /usr/bin/simet_register_ma.sh && {
 		simet_geolocation.sh || :
-		( simetbox_lmap-fetch-schedule.sh \
+		( start-stop-daemon -S -c nicbr-simet:nicbr-simet -n simet_fetch_sched \
+				    -x simetbox_lmap-fetch-schedule.sh \
 			&& chown -h nicbr-simet:nicbr-simet "$LMAP_SCHEDULE_FILE" || :
-		) &
+		) </dev/null >/dev/null 2>&1 &
 	} ) </dev/null >/dev/null 2>&1 &
+
 	start "$@"
 }
 
 start_service() {
-	simet_config
+	simet_config || return $?
 	simet_netconfig
 
 	procd_open_instance simet-inetuptime
